service: copaco-azure-test-function

frameworkVersion: '3'

provider:
  name: azure
  region: West Europe
  runtime: python3.8

plugins:
  - serverless-azure-functions

package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'

functions:
  get_random_quote:
    handler: src/handlers/random_quote.get_random_quote
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: random_quote
          authLevel: function

  get_filtered_quote:
    handler: src/handlers/filtered_quote.get_filtered_quote
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: quote/filtered
          authLevel: function